In [5]:
import numpy as np

In [3]:
my_list = [10,20,30,40]

In [6]:
np.array(my_list)

array([10, 20, 30, 40])

In [7]:
np_list = np.array(my_list)

In [8]:
np_list.max()

np.int64(40)

In [10]:
np.ones(5)  #5 eded 1 reqemi list yaradir

array([1., 1., 1., 1., 1.])

In [11]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [12]:
np.random.random(4)

array([0.23562388, 0.25043322, 0.54295221, 0.57844716])

In [15]:
#array  arthimetic

In [14]:
my_list1 = [1,2]


In [16]:
my_list2 = [2,3]

In [17]:
my_list1+my_list2 #Normal listLərdə toplayanda yan yana yazır

[1, 2, 2, 3]

In [18]:
my_numpy_array1 = np.array(my_list1)

In [19]:
my_numpy_array2 = np.array(my_list2)

In [20]:
my_numpy_array1 + my_numpy_array2  #numpynin listində isə eyni indeksdəki rəqəmləri toplayır

array([3, 5])

In [21]:
my_numpy_array1 * my_numpy_array2

array([2, 6])

In [22]:
my_numpy_array1 - my_numpy_array2

array([-1, -1])

In [23]:
my_numpy_array1 / my_numpy_array2

array([0.5       , 0.66666667])

In [24]:
my_numpy_array1 // my_numpy_array2

array([0, 0])

In [25]:
my_numpy_array1 *4

array([4, 8])

In [27]:
my_list1 * 4

[1, 2, 1, 2, 1, 2, 1, 2]

In [28]:
other_array = np.array([10,20,30,40,50])

In [30]:
print(other_array.max())

50


In [31]:
other_array.min()

np.int64(10)

In [32]:
other_array.sum()

np.int64(150)

In [36]:
my_numpy_array1 + other_array #Bu xəta verəcək çünki birində 2 dəyər var o birində 5

ValueError: operands could not be broadcast together with shapes (2,) (5,) 

In [37]:
#arrange and index

In [39]:
np.arange(0,10) #0-10 araliqinda reqemler 10 nu almir

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [41]:
#random

In [42]:
np.random.randn(4)

array([ 0.81473333,  0.63944619,  1.26500649, -1.04872047])

In [43]:
np.random.randn(4,4)

array([[-0.82035663,  0.97380107,  0.83131662, -0.533168  ],
       [-1.32999851, -1.06754632, -0.43553819, -1.56122889],
       [ 0.44401398, -0.82410084,  1.26044961,  1.04191154],
       [-0.34761288, -0.07838208, -0.39757028,  0.91463194]])

In [46]:
np.random.randint(1,300,5)

array([ 13, 286, 238,  75, 207], dtype=int32)