In [1]:
import numpy as np

In [2]:
my_matrix = [[1,2],[3,4]]

In [5]:
my_matrix[0][1]

2

In [6]:
#row * column  1 2 3  
 #             4 5 6 -->  bu matrisin ölçüsü 2,3  2-row 3-colums

In [8]:
numpy_matrix = np.array([[5,10],[15,20]])

In [9]:
numpy_matrix

array([[ 5, 10],
       [15, 20]])

In [10]:
numpy_matrix[1][0]

np.int64(15)

In [11]:
numpy_matrix.sum() #toplama

np.int64(50)

In [13]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [17]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
#matrinx arthimetric

In [19]:
first_array = np.array([[10,20],[30,40]])

In [43]:
second_array = np.array([[5,15],[25,35]])

In [44]:
first_array + second_array

array([[15, 35],
       [55, 75]])

In [39]:
third_array = np.array([10,20])

In [40]:
first_array + third_array #Gedib həm birici sətir və ikinci sətirlə toplayır

array([[20, 40],
       [40, 60]])

In [25]:
fourth_array = np.array([10,20,30,40,50])


In [26]:
first_array +  fourth_array #Xəta verəcək çünki toplamaq üçün sütunların sayı matrisin sayından az   olmamlıdır

ValueError: operands could not be broadcast together with shapes (2,2) (5,) 

In [27]:
fourth_array * 2 

array([ 20,  40,  60,  80, 100])

In [28]:
first_array *2

array([[20, 40],
       [60, 80]])

In [30]:
first_array / 2

array([[ 5., 10.],
       [15., 20.]])

In [31]:
first_array + 3

array([[13, 23],
       [33, 43]])

In [34]:
third_array = np.array([[10],[20]])

In [35]:
third_array 

array([[10],
       [20]])

In [37]:
first_array

array([[10, 20],
       [30, 40]])

In [36]:
third_array + first_array #bU Səfər birinci sətirə 10 ikinci sətirə 20 əlavə edir

array([[20, 30],
       [50, 60]])

In [41]:
#matris multiplication(matrinslerin vurulmasi)

In [45]:
first_array * second_array

array([[  50,  300],
       [ 750, 1400]])

In [46]:
#dot product

In [47]:
#dot product  productda birinci matrisin  column sayisi ilə ikinci matrisin row sayisi bir birinə bərabər olmalıdır

In [48]:
first_matrix = np.array([[10,20,30]])

In [49]:
first_matrix #1-row 3-column

array([[10, 20, 30]])

In [51]:
first_matrix.shape

(1, 3)

In [52]:
second_matrix = np.array([[2,3],[2,3],[2,3]])

In [53]:
second_matrix

array([[2, 3],
       [2, 3],
       [2, 3]])

In [54]:
second_matrix.shape

(3, 2)

In [57]:
result_matrix =  first_matrix.dot(second_matrix)

In [58]:
result_matrix

array([[120, 180]])

In [59]:
result_matrix.shape

(1, 2)